parameters:
#    juceveju_greeting.example.class: Juceveju\GreetingBundle\Example

services:
#    juceveju_greeting.example:
#        class: %juceveju_greeting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
